pull_request_rules:
  - name: assign PR to its author
    conditions:
      - base = main
    actions:
      assign:
        add_users:
          - "{{author}}"
  - name: review request for all PRs
    conditions:
      - base = main
    actions:
      request_reviews:
        users:
          - GreatAlexander
          - hect95
  - name: automatic merge for pre-commit ci updates
    conditions:
      - author=pre-commit-ci[bot]
      - title=[pre-commit.ci] pre-commit autoupdate
    actions:
      merge:
        method: squash
