/**:
    ros__parameters:
        host_ip: 172.31.0.1
        sensor_ip: 172.31.2.2
        data_port: 2369
        gnss_port: 8308
        packet_mtu_size: 1500
        launch_hw: true
        setup_sensor: true
        udp_only: false
        frame_id: lidar_left
        advanced_diagnostics: true
        diag_span: 1000
        calibration_file: $(find-pkg-share nebula_decoders)/calibration/velodyne/VLP16.yaml
        min_range: 0.3
        max_range: 300.0
        cloud_min_angle: 0
        cloud_max_angle: 360
        scan_phase: 0.0
        sensor_model: VLP16
        rotation_speed: 600
        return_mode: SingleStrongest
