/**:
    ros__parameters:
        device_ip: 172.31.2.3
        gps_time: false
        time_offset: 0.0
        enabled: true
        read_once: false
        read_fast: false
        repeat_delay: 0.0
        frame_id: lidar_right
        model: VLP16
        rpm: 600.0
        port: 2370
        timestamp_first_packet: true
